# Generated by Django 5.1.5 on 2025-05-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='finance_app_date_63a173_idx'),
        ),
    ]
